spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:8080/pos_offline_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level.com.pos.backend=DEBUG
logging.level.org.hibernate.SQL=DEBUG

app.admin.password=Admin123
app.propietario.password=Propietario123
app.cajero.password=Cajero123

# Conexion remota para sincronizacion
spring.datasource.remote.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.remote.username=postgres.khwzwmohqnndyusjjpmr
spring.datasource.remote.password=SystemPos2026.*