spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.khwzwmohqnndyusjjpmr
spring.datasource.password=SystemPos2026.*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level.com.pos.backend=DEBUG
logging.level.org.hibernate.SQL=DEBUG

app.admin.password=${POS_ADMIN_PASSWORD}
app.propietario.password=${POS_PROPIETARIO_PASSWORD}
app.cajero.password=${POS_CAJERO_PASSWORD}